version : "2"
services :
  rpc :
    image : manaphp/php74:210801
    volumes :
      - ./:/var/www/html
      - /data/volumes/${COMPOSE_PROJECT_NAME}/rpc/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/rpc/tmp:/var/www/html/tmp
      - ../framework:/var/www/framework
    command : php /var/www/html/public/index.php
    ports :
      - ${WEB_PORT}:9501
    restart : always