version: "2"
services:
  cli:
    image: manaphp/php73:3.0
    volumes:
      - ../:/var/www/html
      - /data/volumes/${COMPOSE_PROJECT_NAME}/cli/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/cli/tmp:/var/www/html/tmp
      - ../../../ManaPHP:/var/www/html/vendor/manaphp/framework
    command: run cli
    restart: always