version : "3.7"
services :
  __SERVICE_NAME :
    build :
      context : ../
      dockerfile : ./docker/Dockerfile
    image : docker.l/__PROJECT_NAME/__SERVICE_NAME:__IMAGE_TAG
    environment :
      DOTENV_URL : __DOTENV_URL
    volumes :
      - logger:/var/www/html/runtime/logger/
    ports :
      - 8181:9501
    deploy :
      replicas : 1
volumes :
  logger :
