version : "2"
services :
  admin-fpm :
    image : manaphp/php74:210801
    volumes :
      - ../:/var/www/html
      - ./fpm/etc/fpm.conf:/etc/php/fpm.conf
      - ./fpm/etc/php.ini:/etc/php/php.ini
      - /data/volumes/${COMPOSE_PROJECT_NAME}/admin/fpm:/var/log/php
      - /data/volumes/${COMPOSE_PROJECT_NAME}/admin/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/admin/tmp:/var/www/html/tmp
      - ../../framework:/var/www/framework
    command : bash /var/www/html/docker/fpm/bootstrap.sh
    restart : always
  admin-nginx :
    image : nginx:1.19.6
    volumes :
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ../:/var/www/html
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - /data/volumes/${COMPOSE_PROJECT_NAME}/admin/nginx:/var/log/nginx
    ports :
      - ${WEB_PORT}:80
    restart : always