version : "2"
services :
  admin_fpm :
    image : manaphp/php74:4.1
    volumes :
      - ../:/var/www/html
      - ./fpm/conf.d:/etc/php/conf.d
      - /data/volumes/${COMPOSE_PROJECT_NAME}/admin/fpm/:/var/log/php
      - /data/volumes/${COMPOSE_PROJECT_NAME}/admin/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/admin/tmp:/var/www/html/tmp
      - ../../ManaPHP:/var/www/html/vendor/manaphp/framework
    command : /usr/bin/bash -c "chown www-data:www-data data tmp &&exec php-fpm --nodaemonize"
    restart : always
  admin_nginx :
    image : nginx:1.19.6
    volumes :
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ../:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /data/volumes/${COMPOSE_PROJECT_NAME}/admin/nginx/log:/var/log/nginx
    ports :
      - ${WEB_PORT}:80
    restart : always