version: "2"
services:
  user_fpm:
    image: manaphp/php74:3.2
    volumes:
      - ../:/var/www/html
      - ./fpm/conf.d:/etc/php/conf.d
      - /data/volumes/${COMPOSE_PROJECT_NAME}/user/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/user/tmp:/var/www/html/tmp
      - /data/volumes/${COMPOSE_PROJECT_NAME}/user/fpm/:/var/log/php
      - ../../../ManaPHP:/var/www/html/vendor/manaphp/framework
    restart: always
  user_nginx:
    image: nginx:1.17.2
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ../:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh
      - /data/volumes/${COMPOSE_PROJECT_NAME}/user/nginx:/var/log/nginx
    entrypoint: /docker-entrypoint.sh nginx -g "daemon off;"
    ports:
      - ${WEB_PORT}:80
    restart: always