version : "2"
services :
  tcp :
    image : manaphp/php74:4.1
    volumes :
      - ../:/var/www/html
      - /data/volumes/${COMPOSE_PROJECT_NAME}/tcp/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/tcp/tmp:/var/www/html/tmp
      - ../../ManaPHP:/var/www/ManaPHP
    command : php /var/www/html/public/index.php
    ports :
      - 9501:9501
    restart : always